USE [PUANTAJ]
GO

/****** Object:  Table [dbo].[GirisCikisKayitlari]    Script Date: 08.04.2025 18:38:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GirisCikisKayitlari](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KullaniciID] [int] NULL,
	[Yon] [nvarchar](50) NOT NULL,
	[IslemTarihi] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GirisCikisKayitlari] ADD  DEFAULT (getdate()) FOR [IslemTarihi]
GO

ALTER TABLE [dbo].[GirisCikisKayitlari]  WITH CHECK ADD FOREIGN KEY([KullaniciID])
REFERENCES [dbo].[Kullanicilar] ([ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[GirisCikisKayitlari]  WITH CHECK ADD CHECK  (([Yon]='Cikis' OR [Yon]='Giris'))
GO



USE [PUANTAJ]
GO

/****** Object:  Table [dbo].[Kullanicilar]    Script Date: 08.04.2025 18:38:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Kullanicilar](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KullaniciAdi] [nvarchar](100) NOT NULL,
	[Sifre] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[KullaniciAdi] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [PUANTAJ]
GO

/****** Object:  Table [dbo].[QRCodeLog]    Script Date: 08.04.2025 18:39:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[QRCodeLog](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[QRCode] [nvarchar](255) NOT NULL,
	[OlusturmaTarihi] [datetime] NULL,
 CONSTRAINT [PK__QRCodeLo__3214EC27E902822D] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[QRCodeLog] ADD  CONSTRAINT [DF__QRCodeLog__Olust__4E88ABD4]  DEFAULT (getdate()) FOR [OlusturmaTarihi]
GO


